MODEL:
  META_ARCHITECTURE: Baseline

  BACKBONE:
    # NAME: build_mobilenetv2_backbone
    NAME: build_resnet_backbone
    # NAME: build_vit_backbone
    NORM: BN
    # DEPTH: base
    DEPTH: 50x
    LAST_STRIDE: 1
    # FEAT_DIM: 1280
    FEAT_DIM: 2048
    # FEAT_DIM: 768
    WITH_IBN: False
    PRETRAIN: False

  HEADS:
    NAME: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    POOL_LAYER: GlobalAvgPool
    NECK_FEAT: before
    CLS_LAYER: Linear

  LOSSES:
    # NAME: ("TripletLoss",)
    # NAME: ("CrossEntropyLoss", "TripletLoss",
    NAME: ("CrossEntropyLoss", "TripletLoss", "Cosface",)

    CE:
      EPSILON: 0.1
      SCALE: 1.

    TRI:
      MARGIN: 0.5 #default 0.3
      HARD_MINING: True
      NORM_FEAT: True #default False
      SCALE: 1.

INPUT:
  SIZE_TRAIN: [ 256, 128 ]
  SIZE_TEST: [ 256, 128 ]

  REA:
    ENABLED: True
    PROB: 0.5

  FLIP:
    ENABLED: True

  PADDING:
    ENABLED: True

DATALOADER:
  SAMPLER_TRAIN: NaiveIdentitySampler
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  AMP:
    ENABLED: True
  OPT: Adam
  MAX_EPOCH: 5
  # BASE_LR: 0.00035
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.0005
  # WEIGHT_DECAY_NORM: 0.001
  WEIGHT_DECAY_NORM: 0.0005
  IMS_PER_BATCH: 64

  SCHED: MultiStepLR
  STEPS: [ 40, 90 ]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  CHECKPOINT_PERIOD: 30

TEST:
  EVAL_PERIOD: 1000
  IMS_PER_BATCH: 128

CUDNN_BENCHMARK: True
